//! Generates and CI-enforces `docs/CONFORMANCE.md` — the feature-completeness
//! dashboard.
//!
//! Inputs (all committed, so the matrix is deterministic regardless of host):
//!   * `tests/fixtures/attribute_manifest.toml`  — modelled elements/attrs.
//!   * `tests/fixtures/{mini,synthetic,extras}.sdef` — the canonical fixtures.
//!   * `STRONG_TYPED_ENUMS` (below) — closed-enum DTD attrs that the parser
//!     surfaces as a typed Rust `enum` rather than `String`.
//!
//! Output:
//!   * `docs/CONFORMANCE.md` — committed, reviewer-facing.
//!
//! Workflow:
//!   * `cargo test --test conformance_matrix` — fails if the committed file
//!     diverges from the regenerated content.
//!   * `UPDATE_CONFORMANCE_MATRIX=1 cargo test --test conformance_matrix` —
//!     rewrites `docs/CONFORMANCE.md` (commit the result).
//!
//! Live-corpus coverage (`target/corpus_coverage.json` from `corpus_smoke`)
//! is intentionally not part of the committed matrix — it depends on which
//! macOS version and apps the runner has. The conformance dashboard
//! reflects the static, committed surface area.

mod common;

use std::collections::{BTreeMap, BTreeSet};
use std::fs;

use common::{Manifest, scan_xml_coverage};

const OUTPUT_PATH: &str = "docs/CONFORMANCE.md";

/// Hand-crafted fixtures shipped under `tests/fixtures/`. Listed here in the
/// order they appear in the matrix columns.
const FIXTURES: &[(&str, &str)] = &[
    ("mini", "tests/fixtures/mini.sdef"),
    ("synthetic", "tests/fixtures/synthetic.sdef"),
    ("extras", "tests/fixtures/extras.sdef"),
];

/// `element.attribute` keys whose DTD-declared closed-enumeration values are
/// surfaced as a typed Rust enum (rather than a raw `String`). Adding a new
/// entry here requires both an AST change AND a manifest update — the
/// attribute_conformance test pins the manifest enum list against the DTD.
const STRONG_TYPED_ENUMS: &[&str] = &["accessor.style"];

#[test]
fn matrix_is_up_to_date() {
    let manifest = Manifest::load();

    let mut fixture_coverage: BTreeMap<&str, BTreeMap<String, BTreeSet<String>>> = BTreeMap::new();
    for (name, path) in FIXTURES {
        let xml = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
        fixture_coverage.insert(*name, scan_xml_coverage(&xml));
    }

    let regenerated = render(&manifest, &fixture_coverage);

    if std::env::var_os("UPDATE_CONFORMANCE_MATRIX").is_some() {
        if let Some(parent) = std::path::Path::new(OUTPUT_PATH).parent() {
            fs::create_dir_all(parent).expect("create docs/");
        }
        fs::write(OUTPUT_PATH, &regenerated).expect("write docs/CONFORMANCE.md");
        eprintln!("regenerated {OUTPUT_PATH}");
        return;
    }

    let committed = fs::read_to_string(OUTPUT_PATH).unwrap_or_else(|e| {
        panic!(
            "could not read {OUTPUT_PATH}: {e}. Run \
             `UPDATE_CONFORMANCE_MATRIX=1 cargo test --test conformance_matrix` to generate it."
        )
    });

    if committed != regenerated {
        panic!(
            "{OUTPUT_PATH} is out of sync with the regenerated matrix.\n\n\
             Regenerate with:\n  \
             UPDATE_CONFORMANCE_MATRIX=1 cargo test --test conformance_matrix\n\n\
             Then `git diff -- {OUTPUT_PATH}` to review the change."
        );
    }
}

fn render(
    manifest: &Manifest,
    fixtures: &BTreeMap<&str, BTreeMap<String, BTreeSet<String>>>,
) -> String {
    let mut s = String::new();

    // ===== Header =====
    s.push_str("# DTD Conformance Matrix\n\n");
    s.push_str(
        "**Generated by `tests/conformance_matrix.rs`.** Do not hand-edit. \
         Regenerate with `UPDATE_CONFORMANCE_MATRIX=1 cargo test --test conformance_matrix`. \
         CI fails when this file drifts from the regenerated output.\n\n",
    );
    s.push_str(
        "Source DTD: `/System/Library/DTDs/sdef.dtd` (macOS 26.5, sha256 pinned in \
         `tests/fixtures/sdef.dtd.sha256`).\n\n",
    );

    // ===== Scoreboard =====
    let total_elements = manifest.elements.len();
    let total_attrs: usize = manifest.elements.iter().map(|e| e.attributes.len()).sum();
    let total_enums = manifest.enums.len();
    let strong_set: BTreeSet<&str> = STRONG_TYPED_ENUMS.iter().copied().collect();
    let total_strong = strong_set.len();
    let elements_in_any_fixture = manifest
        .elements
        .iter()
        .filter(|e| fixtures.values().any(|m| m.contains_key(&e.name)))
        .count();

    s.push_str("## At a glance\n\n");
    s.push_str(&format!(
        "- **{total_elements}/{total_elements}** DTD elements modelled.\n"
    ));
    s.push_str(&format!(
        "- **{total_attrs}** DTD-declared attributes modelled (every attribute of every modelled element; verified by `tests/attribute_conformance.rs`).\n"
    ));
    s.push_str(&format!(
        "- **{total_strong}/{total_enums}** closed-enum attributes surfaced as typed Rust enums; the remainder stay as `String` for forward compatibility (see *Known limitations* below).\n"
    ));
    s.push_str(&format!(
        "- **{elements_in_any_fixture}/{total_elements}** elements exercised by ≥1 committed fixture under `tests/fixtures/`.\n\n"
    ));

    // ===== Per-element table =====
    s.push_str("## Elements\n\n");
    s.push_str("One row per DTD element. Columns:\n\n");
    s.push_str("- **Required attrs** — DTD-declared `#REQUIRED` attributes.\n");
    s.push_str("- **Other attrs** — DTD-declared `#IMPLIED` attributes.\n");
    s.push_str("- **Typed enums** — closed-enum attributes that the parser surfaces as a typed Rust enum (rather than `String`). `(none)` is the common case.\n");
    s.push_str("- **mini / synthetic / extras** — whether the element appears in the named fixture under `tests/fixtures/`.\n\n");
    s.push_str(
        "| Element | Required attrs | Other attrs | Typed enums | mini | synthetic | extras |\n",
    );
    s.push_str("|---|---|---|---|---|---|---|\n");

    for spec in &manifest.elements {
        let required: BTreeSet<&str> = spec.required.iter().map(String::as_str).collect();
        let req_col = if required.is_empty() {
            "—".to_string()
        } else {
            join_codes(
                spec.attributes
                    .iter()
                    .filter(|a| required.contains(a.as_str())),
            )
        };
        let other_col = {
            let others: Vec<&String> = spec
                .attributes
                .iter()
                .filter(|a| !required.contains(a.as_str()))
                .collect();
            if others.is_empty() {
                "—".to_string()
            } else {
                join_codes(others.into_iter())
            }
        };
        let typed = strong_typed_for_element(&spec.name, &strong_set);
        let typed_col = if typed.is_empty() {
            "(none)".to_string()
        } else {
            typed.join(", ")
        };
        let mut cells = Vec::<&str>::new();
        for (name, _) in FIXTURES {
            let covered = fixtures
                .get(name)
                .is_some_and(|m| m.contains_key(&spec.name));
            cells.push(if covered { "✅" } else { "—" });
        }
        s.push_str(&format!(
            "| `{}` | {req_col} | {other_col} | {typed_col} | {} | {} | {} |\n",
            spec.name, cells[0], cells[1], cells[2],
        ));
    }
    s.push('\n');

    // ===== Per-attribute fixture coverage =====
    s.push_str("## Per-attribute fixture coverage\n\n");
    s.push_str(
        "Granular view: one row per `(element, attribute)` pair, showing which committed \
         fixture exercises that attribute. Use this to spot blind spots — rows with no ✅ \
         indicate attributes the fixtures don't yet cover.\n\n",
    );
    s.push_str("| Element . attribute | mini | synthetic | extras |\n");
    s.push_str("|---|---|---|---|\n");
    for spec in &manifest.elements {
        if spec.attributes.is_empty() {
            continue;
        }
        for attr in &spec.attributes {
            let mut cells = Vec::<&str>::new();
            for (name, _) in FIXTURES {
                let covered = fixtures
                    .get(name)
                    .and_then(|m| m.get(&spec.name))
                    .is_some_and(|attrs| attrs.contains(attr));
                cells.push(if covered { "✅" } else { "—" });
            }
            s.push_str(&format!(
                "| `{}.{}` | {} | {} | {} |\n",
                spec.name, attr, cells[0], cells[1], cells[2],
            ));
        }
    }
    s.push('\n');

    // ===== Closed-enum constraints =====
    s.push_str("## Closed-enum attribute constraints\n\n");
    s.push_str(
        "Attributes whose DTD type restricts the value to a fixed set. `Typed at parse time` \
         is ✅ when the parser surfaces a typed Rust enum; ❌ when it accepts the value as \
         a raw `String` (lenient by design — strict-mode parsing additionally rejects \
         unknown values on entries marked ✅).\n\n",
    );
    s.push_str("| Element . attribute | Allowed values | Typed at parse time |\n");
    s.push_str("|---|---|---|\n");
    let mut enum_keys: Vec<&String> = manifest.enums.keys().collect();
    enum_keys.sort();
    for key in enum_keys {
        let values = &manifest.enums[key];
        let value_col = values
            .iter()
            .map(|v| format!("`{v}`"))
            .collect::<Vec<_>>()
            .join(" \\| ");
        let typed = if strong_set.contains(key.as_str()) {
            "✅"
        } else {
            "❌"
        };
        s.push_str(&format!("| `{key}` | {value_col} | {typed} |\n"));
    }
    s.push('\n');

    // ===== Known limitations =====
    s.push_str("## Known limitations\n\n");
    s.push_str(
        "- **XInclude** (`<xi:include>`) is not resolved. Strict mode rejects it via \
         [`Error::XIncludeUnsupported`]; lenient mode silently treats includes as no-ops. \
         Resolve includes externally before parsing if needed.\n",
    );
    s.push_str(
        "- **Nested-list type expressions** (`<type list=\"yes\">…<type list=\"yes\"/>…`) are not \
         represented as a recursive structure. Cocoa Scripting itself ignores nested lists; \
         the limitation is documented inline on `TypeRef.list`.\n",
    );
    s.push_str(
        "- **Multi-OS DTD pinning**: only the macOS 26.5 `sdef.dtd` SHA-256 is hash-checked. \
         Earlier macOS releases ship subsets of the DTD; the modelled AST is forward-compatible \
         with the union as documented in the README.\n",
    );
    s.push_str(
        "- **Live-corpus coverage** is generated by the `corpus-macos.yml` workflow (weekly cron \
         + workflow_dispatch) and uploaded as the `corpus-coverage` artifact. It is not part of \
         this committed matrix because corpus availability depends on the runner image \
         (system sdefs and which apps are installed).\n",
    );

    s
}

fn join_codes<'a, I: Iterator<Item = &'a String>>(it: I) -> String {
    let parts: Vec<String> = it.map(|s| format!("`{s}`")).collect();
    parts.join(", ")
}

fn strong_typed_for_element(elem: &str, strong: &BTreeSet<&str>) -> Vec<String> {
    let prefix = format!("{elem}.");
    strong
        .iter()
        .filter(|k| k.starts_with(&prefix))
        .map(|k| {
            let attr = &k[prefix.len()..];
            format!("`{attr}`")
        })
        .collect()
}
